//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectsMVC.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDescargas
    {
        public int descCodigo { get; set; }
        public Nullable<int> prueCodigo { get; set; }
        public string descDescripcion { get; set; }
        public string descLink { get; set; }
    
        public virtual tbPrueba tbPrueba { get; set; }
    }
}
